In [35]:
import os
import ExtractMsg

docs=[]
docsQuote=[]
docsQuoteSubject=[]
docsNoQuoteSubject=[]
testDocSubject=[]
docsNoQuote =[]
testDoc =[]
sendTimeQuote = []
sendTimeTest = []
sendTimeNoQuote = []
attachmentsQuote = []
attachmentsNoQuote=[]
attachmentsTest=[]
pathQuote = 'C:/Users/StefanLap/Desktop/Bachelorarbeit/TrainQuote/'
pathNoQuote = 'C:/Users/StefanLap/Desktop/Bachelorarbeit/TrainNoQuote/'
pathTest = 'C:/Users/StefanLap/Desktop/Bachelorarbeit/TestPredict/'

def flag_attachment(mail):
    if  not mail.attachments:
        return 0
    else :
        return 1    


def filldoclist(filepath, fillList, subjectList, timelist, attachmentlist) :
        for file in os.listdir(filepath):
            mail = ExtractMsg.Message(filepath+file)
            try:
                
                fillList.append(mail.body)
                subjectList.append(file)
                timelist.append(mail.date)
                attachmentlist.append(flag_attachment(mail))
                continue
            except UnicodeDecodeError:
                continue                
            
            
filldoclist(pathQuote, docsQuote, docsQuoteSubject, sendTimeQuote, attachmentsQuote)
filldoclist(pathNoQuote, docsNoQuote, docsNoQuoteSubject, sendTimeNoQuote, attachmentsNoQuote)
filldoclist(pathTest, testDoc, testDocSubject, sendTimeTest, attachmentsTest)

        
docs = docsQuote + docsNoQuote
trainSubjects = docsQuoteSubject + docsNoQuoteSubject
trainSendTime = sendTimeQuote + sendTimeNoQuote
trainAttachments = attachmentsQuote + attachmentsNoQuote




    

In [36]:
import numpy as np
import nltk
#Zählt wie viele ? im Text auftreten
def count_question(content):
    my_list = []
    for text in content:
        count = 0
        tokens = nltk.word_tokenize(text)
        for word in tokens:
            if(word == "?"):
                count = count + 1
            else:
                continue
        my_list.append(count)
    return np.asarray(my_list) 




In [50]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction import stop_words
from sklearn.feature_extraction import text
from dateutil.parser import parse

import numpy as np
import pandas as pd
from scipy.sparse import hstack


targetlist=[]

for i in range(0,len(docsQuote)):
    targetlist.append(1)

for i in range(0,len(docsNoQuote)):
    targetlist.append(0)

# Labels werden in array umgewandelt dass classifier es benutzen können shape = traindoclänge x 1
train_y = np.asarray(targetlist)

# Uhrzeit wird in 3 int Werte umgewandelt und einzeln abgespeichert shape = doclänge x 3
def parse_send_time(timelist):
    n = len(timelist)
    m = 3
    parsed_list = [[0] * m for i in range(n)]
    for i in range(n):
        time =  timelist[i]
        if(time != None):
            dt = parse(time)            
            parsed_list[i][0] =dt.strftime('%H')
            parsed_list[i][1]=dt.strftime('%M')
            parsed_list[i][2]=dt.strftime('%S')
            
        else :
            parsed_list[i][0] = 0
            parsed_list[i][1]= 0
            parsed_list[i][2]= 0
    return np.asarray(parsed_list)




#training und test content im Block da Tfidftransformer bei beiden gebraucht werden

file =open('C:/Users/StefanLap/Desktop/Bachelorarbeit/stopwords.txt', 'r', encoding='utf8')
stop_words_ger = file.read()

my_stop_words = frozenset(nltk.word_tokenize(stop_words_ger))



count_vect = CountVectorizer(stop_words=my_stop_words )
content_count = count_vect.fit_transform(docs)
tf_transformer = TfidfTransformer(use_idf=False).fit(content_count)
content_tfidf = tf_transformer.transform(content_count).toarray()


test_content_counts = count_vect.transform(testDoc)
test_content_tfidf = tf_transformer.transform(test_content_counts).toarray()


#training und test subject im Block da Tfidftransformer bei beiden gebraucht wird

count_vect_subject = CountVectorizer( )
subject_count = count_vect_subject.fit_transform(trainSubjects)
tf_subject_transformer =TfidfTransformer(use_idf=False).fit(subject_count)
subject_tfidf = tf_subject_transformer.transform(subject_count).toarray()

test_subject_counts = count_vect_subject.transform(testDocSubject)
test_subject_tfidf = tf_subject_transformer.transform(test_subject_counts).toarray()

#verusch tfidf des Inhalts und Countvectorizer des Betreffs zu kombinieren




#print(content_tfidf.shape)
#print(test_content_tfidf.shape)
#print(subject_tfidf.shape)
#print(test_subject_tfidf.shape)



train_attachments = np.asarray([trainAttachments])
train_send_time = parse_send_time(trainSendTime)
numpyTarget = np.asarray([targetlist])


test_attachments = np.asarray([attachmentsTest])
test_send_time = parse_send_time(sendTimeTest)



test_content_subject_set = np.hstack((test_content_tfidf, test_subject_tfidf))
test_content_subject_time_set = np.hstack((test_content_tfidf, test_subject_tfidf, test_send_time))
test_content_subject_time_attachments_set = np.concatenate((test_content_subject_time_set, test_attachments.T ), axis=1)

      




train_content_subject_set = np.hstack((content_tfidf, subject_tfidf))
train_content_subject_time_set = np.hstack((content_tfidf, subject_tfidf, train_send_time))
train_content_subject_label_set =np.concatenate((train_content_subject_set, numpyTarget.T), axis=1)
train_content_subject_time_attachments_set = np.concatenate((train_content_subject_time_set, train_attachments.T ), axis=1)

x_test =  np.array(test_content_subject_set).astype(np.float) 
x_train = np.array(train_content_subject_set).astype(np.float)


print(train_content_subject_set.shape)



(214, 7874)


In [51]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB

def fit_neuronal(training_dataset, targetlist):
    temp_neuronal = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(5, 2), random_state=1)
    temp_neuronal.fit(training_dataset, targetlist)
    return temp_neuronal

def fit_svm(training_dataset, targetlist):
    scaler = StandardScaler()
    X = scaler.fit_transform(training_dataset)
    temp_svm = SVC()
    temp_svm.fit(X, targetlist)
    return temp_svm


def fit_knn(training_dataset, targetlist):
    temp_knn= KNeighborsClassifier(n_neighbors=7)
    temp_knn.fit(training_dataset, targetlist)
    return temp_knn

def fit_NB(training_dataset, targetlist, bernoulli):
    if (bernoulli == True) :
        temp_NB = BernoulliNB()
        temp_NB.fit(training_dataset, targetlist)
        return temp_NB
    else :
        temp_NB = GaussianNB()
        temp_NB.fit(training_dataset, targetlist)
        return temp_NB
    
nb = fit_NB(x_train, targetlist, False)
nb_B = fit_NB(x_train, targetlist, True)
knn = fit_knn(x_train, targetlist)
svm = fit_svm(x_train, targetlist)

neuronal = fit_neuronal(x_train, targetlist)






In [52]:
#predicted_knn = knn.predict(test_content_subject_time_set)
predicted_nb = nb.predict(x_test)
predicted_nb_B = nb_B.predict(x_test)
#predicted_svm = svm.predict(x_test)
#predicted_neuronal = neuronal.predict(x_test)
print("GaussianNB")
print( predicted_nb)
#print(predicted_knn)
print("BernoulliNB")
print( predicted_nb_B)
#print(predicted_svm)
#print(predicted_neuronal)

GaussianNB
[1 0 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 1]
BernoulliNB
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1]


In [5]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
k_fold = KFold(n_splits=10, shuffle=True, random_state=0)
ss = ShuffleSplit(n_splits=10, test_size=0.25, random_state=0)


In [6]:
scoring = 'accuracy'
score_knn= cross_val_score(knn, train_content_subject_set, targetlist, cv=ss, n_jobs=1, scoring=scoring)
score_nb_B= cross_val_score(nb_B, train_content_subject_set, targetlist, cv=ss, n_jobs=1, scoring=scoring)
score_nb= cross_val_score(nb, train_content_subject_set, targetlist, cv=ss, n_jobs=1, scoring=scoring)
score_svm= cross_val_score(svm, train_content_subject_set, targetlist, cv=k_fold, n_jobs=1, scoring=scoring)
#score_neuronal= cross_val_score(neuronal, train_content_subject_set, targetlist, cv=k_fold, n_jobs=1, scoring=scoring)
print(score_knn)
print(score_nb)
print(score_nb_B)
print(score_svm)
#print(score_neuronal)
#print("Accuracy: %0.2f (+/- %0.2f)" % (score_nb.mean(), scores.std() * 2))

[ 0.83333333  0.7962963   0.74074074  0.74074074  0.74074074  0.75925926
  0.92592593  0.72222222  0.81481481  0.81481481]
[ 0.81481481  0.85185185  0.74074074  0.90740741  0.75925926  0.88888889
  0.85185185  0.7962963   0.81481481  0.81481481]
[ 0.77777778  0.83333333  0.72222222  0.88888889  0.85185185  0.81481481
  0.81481481  0.87037037  0.81481481  0.7962963 ]
[ 0.59090909  0.54545455  0.40909091  0.54545455  0.57142857  0.38095238
  0.52380952  0.52380952  0.61904762  0.47619048]


In [7]:
print(round(np.mean(score_knn)*100, 2))
print(round(np.mean(score_nb_B)*100, 2))
print(round(np.mean(score_nb)*100, 2))
print(round(np.mean(score_svm)*100, 2))
#print(round(np.mean(score_neuronal)*100, 2))

78.89
81.85
82.41
51.86


In [8]:
from sklearn.metrics import average_precision_score
y_test= [1,0,0]
print(x_test.shape)
#y_score = knn.descision_function(x_test,y_test)
#average_precision = average_precision_score()

(25, 8398)


In [12]:
from sklearn.model_selection import GridSearchCV

scores = ['precision', 'recall']




tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-3, 1e-4],
                     'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}]
clf = GridSearchCV(SVC(),tuned_parameters , cv=5)
                    
clf.fit(train_content_subject_set, targetlist)

print(clf.best_params_)
print(clf.cv_results_['mean_test_score'])
print(clf.cv_results_['std_test_score'])


{'C': 1, 'kernel': 'linear'}
[ 0.51869159  0.51869159  0.51869159  0.51869159  0.79439252  0.51869159
  0.78971963  0.79439252  0.81308411  0.74766355  0.74766355  0.74766355]
[ 0.00580359  0.00580359  0.00580359  0.00580359  0.09687561  0.00580359
  0.05371676  0.09687561  0.07434394  0.06988659  0.08036899  0.08036899]


In [21]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import expon 
# specify parameters and distributions to sample from
print(clf.get_params().keys())
param_dist = {'C': expon(scale=100), 'gamma': expon(scale=.1),
  'kernel': ['rbf'], 'class_weight':['balanced', None]}

# run randomized search
n_iter_search = 20
random_search = RandomizedSearchCV(clf, param_distributions=param_dist,
                                   n_iter=n_iter_search)

random_search.fit(train_content_subject_set, targetlist)

print(random_search.cv.results_)

dict_keys(['cv', 'error_score', 'estimator__C', 'estimator__cache_size', 'estimator__class_weight', 'estimator__coef0', 'estimator__decision_function_shape', 'estimator__degree', 'estimator__gamma', 'estimator__kernel', 'estimator__max_iter', 'estimator__probability', 'estimator__random_state', 'estimator__shrinking', 'estimator__tol', 'estimator__verbose', 'estimator', 'fit_params', 'iid', 'n_jobs', 'param_grid', 'pre_dispatch', 'refit', 'return_train_score', 'scoring', 'verbose'])


ValueError: Invalid parameter C for estimator GridSearchCV(cv=5, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'kernel': ['rbf'], 'gamma': [0.001, 0.0001], 'C': [1, 10, 100, 1000]}, {'kernel': ['linear'], 'C': [1, 10, 100, 1000]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0). Check the list of available parameters with `estimator.get_params().keys()`.

In [73]:
from sklearn.model_selection import GridSearchCV


gs = GridSearchCV(MLPClassifier(), param_grid={
    'learning_rate': ["constant", "invscaling", "adaptive"],
    'hidden_layer_sizes': [(30,40,50,60)], #[x for x in itertools.product((10,20,30,40,50,100),repeat=3)]

'activation': ["logistic", "relu", "tanh"]})
gs.fit(x_train, targetlist)



array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1])

In [74]:
x=gs.predict(x_test)
print(x)

[1 0 0 1 0 0 1 1 0 0 1 1 1 0 0 1 1 1 1 1 1 0 1 0 1]
